import "@/styles/globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Souaba",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className="font-Montserrat">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
